# https://pytest-with-eric.com/integrations/pytest-github-actions/
---

name: Run Unit Test via Pytest

on:
  push:
    branches:
      - "main"
      - "devel"
    paths:
      - "03-todos-database"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r 03-todos-database/requirements.txt

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff 03-todos-database/src --format=github --target-version=py310
        continue-on-error: true

      - name: Test with pytest and Coverage
        run: |
          pip install coverage
          coverage run -m pytest 03-todos-database/tests -v -s

      - name: Generate Coverage Report
        run: |
          coverage report --source=03-todos-database/src -m
